
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # [14.x, 16.x, 18.x]
    steps:
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: f14607376f172e8ff8bd099b3c287034
        filename: test.json
        label: Hello
        message: World
        color: orange
